@startuml Zustandsdiagramm
' Preview durch <Alt>d

hide empty description
state BuchFrontend {
    BuchFrontend : name = "buch-frontend"
    BuchFrontend : version = "1.0.1"

    state App {
        [*] --> Logout

        state BuchSuche {
            [*] --> Suchformular: Suchkriterien eingeben
            Suchformular --> Warten: Button "Suche"
            Suchformular --> BuchSuche: Button "Zurücksetzen"
            state SuchAuswahl <<choice>>
            Warten --> SuchAuswahl: Suchergebnis eingetroffen

            state SuchergebnisTabelle {
                SuchAuswahl --> GefundeneBuecher: mind. 1 passendes Buch gefunden
                SuchAuswahl --> Fehlermeldung: keine passenden Bücher gefunden
                Fehlermeldung --> [*]
            }
        }
        Details --> Bearbeiten: Button "Bearbeiten"
        Details --> Löschen: Button "Löschen"
        Löschen --> BuchSuche: Buch löschen

        state Bearbeiten {
            [*] --> Datenfelder: Änderungen eintragen
            state UpdateAuswahl <<choice>> 
            Datenfelder --> UpdateAuswahl: Button "Änderungen speichern"
            UpdateAuswahl --> UpdateFehlermeldung: Fehlerhafte Daten
            UpdateAuswahl --> UpdateBuch: Gültige Daten
            UpdateBuch --> Bearbeiten: Daten hochladen
            UpdateFehlermeldung --> Bearbeiten: Daten korrigieren
        }

        [*] --> BuchSuche: Navigationsleiste "Erweiterte Suche"
        GefundeneBuecher --> Details: Buch in der Tabelle auswählen

        [*] --> NeuesBuchHinzufuegen: Navigationsleiste "Neues Buch"
        
        state NeuesBuchHinzufuegen {
            [*] --> Eingabefelder: Daten eines Buches eintragen
            state HinzufuegenAuswahl <<choice>>
            Eingabefelder --> HinzufuegenAuswahl: Button "Buch anlegen"
            HinzufuegenAuswahl --> BuchErstellen: Gültige Daten
            HinzufuegenAuswahl --> FehlerMeldung: Ungültige Daten
            BuchErstellen --> NeuesBuchHinzufuegen: Buch wird hochgeladen
            FehlerMeldung --> NeuesBuchHinzufuegen: Daten korrigieren
        }

        
    }
}
@enduml
